CREATE TABLE `osa_wages` (
  `pay_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '工资表id',
  `pay_username` VARCHAR(255) DEFAULT  NULL  COMMENT '员工姓名',
  `pay_month` int(11) DEFAULT NULL COMMENT '月份',
  `pay_base_wage` DECIMAL(11,4) DEFAULT NULL  COMMENT '基本工资',
  `pay_job_wage` DECIMAL(11,4) DEFAULT NULL  COMMENT '职位工资',
  `pay_performance_wage` DECIMAL(11,4) DEFAULT NULL  COMMENT '绩效工资',
  `pay_extract` DECIMAL(11,4) DEFAULT NULL  COMMENT '提成/奖金',
  `pay_subsidy_computer` DECIMAL(11,4) DEFAULT NULL  COMMENT '电脑补助',
  `pay_subsidy_technology` DECIMAL(11,4) DEFAULT NULL  COMMENT '技术补助',
  `pay_subsidy_comm` DECIMAL(11,4) DEFAULT NULL  COMMENT '通讯补助',
  `pay_subsidy_traffic` DECIMAL(11,4) DEFAULT NULL  COMMENT '交通补助',
  `pay_day_number_sj` DECIMAL(11,4) DEFAULT NULL  COMMENT '事假天数',
  `pay_day_number_bj` DECIMAL(11,4) DEFAULT NULL  COMMENT '病假天数',
  `pay_day_number_tx` DECIMAL(11,4) DEFAULT NULL  COMMENT '调休天数',
  `pay_day_number` DECIMAL(11,4) DEFAULT NULL  COMMENT '计薪天数',
  `pay_day_number_system` DECIMAL(11,4) DEFAULT NULL  COMMENT '系统工时',
  `pay_day_number_workoff_money` DECIMAL(11,4) DEFAULT NULL  COMMENT '带薪假期',
  `pay_day_number_infact` DECIMAL(11,4) DEFAULT NULL  COMMENT '实际出勤天数',
  `pay_wage_number` DECIMAL(11,4) DEFAULT NULL  COMMENT '计薪工资',
  `pay_eat_money` DECIMAL(11,4) DEFAULT NULL  COMMENT '餐补',
  `pay_all_work` DECIMAL(11,4) DEFAULT NULL  COMMENT '全勤奖',
  `pay_onther_money_add` DECIMAL(11,4) DEFAULT NULL  COMMENT '其他补发项目',
  `pay_weekr_report` DECIMAL(11,4) DEFAULT NULL  COMMENT '周报扣款',
  `pay_money_late_delete` DECIMAL(11,4) DEFAULT NULL  COMMENT '迟到未打卡扣款',
  `pay_money_delete` DECIMAL(11,4) DEFAULT NULL  COMMENT '其他扣款',
  `pay_money_person_delete` DECIMAL(11,4) DEFAULT NULL  COMMENT '个人扣款',
  `pay_wage_shouldbe` DECIMAL(11,4) DEFAULT NULL  COMMENT '应发工资',
  `pay_money_housing` DECIMAL(11,4) DEFAULT NULL  COMMENT '住房公积金',
  `pay_money_lost_word` DECIMAL(11,4) DEFAULT NULL  COMMENT '养老保险',
  `pay_money_yl` DECIMAL(11,4) DEFAULT NULL  COMMENT '失业保险',
  `pay_money_mz` DECIMAL(11,4) DEFAULT NULL  COMMENT '门诊/医疗保险',
  `pay_money_hospital` DECIMAL(11,4) DEFAULT NULL  COMMENT '住院',
  `pay_money_all` DECIMAL(11,4) DEFAULT NULL  COMMENT '税前工资',
  `pay_money_gs` DECIMAL(11,4) DEFAULT NULL  COMMENT '个税',
  `pay_wage_infact` DECIMAL(11,4) DEFAULT NULL  COMMENT '个税',
  `pay_money_gs` DECIMAL(11,4) DEFAULT NULL  COMMENT '实发工资',
  `pay_create_timestamp` DECIMAL(11,4) DEFAULT NULL  COMMENT '录入时间',
  PRIMARY KEY (`pay_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;